modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hdr_mod"
version = "${version}"
displayName = "HDR Mod"
authors = "rrtt217"
description = '''
Enable native HDR in Minecraft with Iris shaders.
'''
#logoFile = ""

[[dependencies.hdr_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hdr_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,1.21.10]"
ordering = "NONE"
side = "BOTH"

[[dependencies.hdr_mod]]
modId = "cloth_config"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.hdr_mod]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "hdr_mod.mixins.json"
